USE [SIAM_EPSDB]
GO
/****** Object:  StoredProcedure [dbo].[wiss_sa_eps_report_budget_checking_pr_detail]    Script Date: 24/05/2022 4:10:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =========================================================
-- [wiss_sa_eps_report_budget_checking_pr_detail]
-- Created by :  PnATTAWUT JAIDEE
-- Created date : 09-05-2022
-- Updated date : 09-05-2022
-- =========================================================
ALTER PROCEDURE [dbo].[wiss_sa_eps_report_budget_checking_pr_detail]
@doc_num AS VARCHAR(30)
AS

    SELECT POF.PONUM,  dbo.fn_set_date_txt(POF.PODATE) AS PODATE , INVL.INVNUM AS INVNUM, dbo.fn_set_date_txt(INVH.DOCDATE) AS INVOICEDATE,
  RCL.RCNUM, PRIL.PRNUM, dbo.fn_set_date_txt(PRFL.CREATEDDATE) AS PRDATE,  dbo.fn_set_date_txt(PRIL.CREATEDDATE) AS APPROVEDDATE,  POF.VENDORID AS VDCODE,
  POF.VENDOR_NAME AS VDNAME,  POFL.ITEMNO,   POFL.MATDESC AS ITEMDESC,  POFL.UNIT AS RCPUNIT, POFL.PRICE AS UNITCOST,   RCL.QRECEIVED AS RQRECEIVED,
  RCL.AMOUNT, PRIL.BUDGETTYPE,
  CASE POF.BUDGETTYPE WHEN 'EXPENSE'  THEN
  CASE  WHEN LEN (POFL.ACCOUNTCODE) > 10   THEN POFL.ACCOUNTCODE ELSE   LEFT(POFL.ACCOUNTCODE,5)+'-'+ RIGHT(POFL.ACCOUNTCODE,4)  END
  WHEN 'INVESTMENT'  THEN POFL.ACCOUNTCODE END  AS ACCOUNT,POF.SECTIONID
  FROM TT_POFORM POF
  LEFT JOIN TT_POFORM_LINE POFL  ON POF.PONUM = POFL.PONUM
  LEFT JOIN TT_RCFORM_LINE RCL  ON POFL.POLINE_ROWID = RCL.POLINE_ROWID
  LEFT JOIN TT_INVFORM_LINE INVL  ON INVL.RCLINE_ROWID = RCL.RCLINE_ROWID
  LEFT JOIN TT_INVFORM INVH ON INVH.INVNUM = INVL.INVNUM AND INVH.RCNUM = INVL.RCNUM
  LEFT JOIN TT_PRITEM_LINE PRIL ON POFL.PRITEMLINE_ROWID = PRIL.PRITEM_LINE_ROWID
  LEFT JOIN TT_PRFORM_LINE PRFL ON PRIL.PRFORM_LINE_ROWID = PRFL.PRFORM_LINE_ROWID
  WHERE POFL.PRNUM = @doc_num
        --and POFL.createddate>=@start_date AND
        --POFL.createddate<=@end_date




-- EXEC wiss_sa_eps_report_budget_checking_pr_detail 'PR22000571'

